config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'lists#index'
  resources :movies do
    resources :bookmarks, only: [:new, :create]
  end

  resources :lists do
    resources :bookmarks, only: [:destroy]
  end

  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  validates :comment, length: { minimum: 6 }
  belongs_to :movie
  belongs_to :list

  validates_uniqueness_of :movie_id, scope: [:list_id]
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  def image_url
    return "https://example.com/default.jpg" if movies.empty?

    movies.first.poster_url
  end
end

app/models/movie.rb
class Movie < ApplicationRecord
  before_destroy :ensure_no_bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
  has_many :bookmarks, dependent: :restrict_with_error
  has_many :lists, through: :bookmarks

  private

  def ensure_no_bookmarks
    unless bookmarks.empty?
      errors.add(:base, "Cannot delete movie with bookmarks")
      throw :abort
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [:new, :create]
  before_action :set_bookmark, only: [:new, :destroy]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    if @bookmark.save
      redirect_to list_path(@bookmark.list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :list_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to @list
    else
      render :new
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      redirect_to @list
    else
      render :edit
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name,)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to @movie
    else
      render :new
    end
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to @movie
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :overview, :poster_url, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for bookmark do |f| %>
  <%= f.association :movie %>
  <%= f.association :list %>
  <%= f.input :comment %>
  <%= f.button :submit, formaction: bookmark_path(bookmark) %>
<% end %>

app/views/bookmarks/edit.html.erb
<div class="container">
  <h1>Editing Bookmark</h1>
  <%= render 'form', bookmark: @bookmark %>
</div>

app/views/bookmarks/new.html.erb
<div class="container">
  <h1>New Bookmark</h1>
  <%= render 'form', bookmark: @bookmark %>
</div>

app/views/bookmarks/show.html.erb
<div class="container">
  <h1>Bookmark</h1>
  <p>Movie: <%= @bookmark.movie.title %></p>
  <p>List: <%= @bookmark.list.name %></p>
  <p>Comment: <%= @bookmark.comment %></p>
  <%= link_to 'Edit', edit_bookmark_path(@bookmark), class: 'btn btn-secondary' %>
  <%= link_to 'Destroy', bookmark_path(@bookmark), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for list do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/lists/edit.html.erb
<div class="container">
  <h1>Editing List</h1>
  <%= render 'form', list: @list %>
</div>

app/views/lists/index.html.erb
<div class="container">
  <h1>Lists</h1>
  <%= link_to 'New List', new_list_path, class: 'btn btn-primary' %>
  <div class="row">
    <% @lists.each do |list| %>
      <div class="col-md-4">
        <div class="card mb-3">
          <img src="<%= list.image_url %>" class="card-img-top" alt="<%= list.name %>">
          <div class="card-body">
            <h5 class="card-title"><%= list.name %></h5>
            <p class="card-text"><%= pluralize(list.movies.count, 'movie') %> in this list</p>
            <%= link_to 'Show', list_path(list), class: 'btn btn-secondary' %>
            <%= link_to 'Edit', edit_list_path(list), class: 'btn btn-secondary' %>
            <%= link_to 'Destroy', list_path(list), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container">
  <h1>New List</h1>
  <%= render 'form', list: @list %>
</div>

app/views/lists/show.html.erb
<div class="container">
  <h1><%= @list.name %></h1>
  <%= link_to 'Go back', lists_path(@list), class: 'btn btn-primary' %>
  <img src="<%= @list.image_url %>" class="img-fluid" alt="<%= @list.name %>">
  <h2>Movies</h2>
  <div class="row">
    <% @list.movies.each do |movie| %>
      <%= render partial: "movies/movie", locals: { movie: movie } %>
      <% bookmark = movie.bookmarks.find_by(list_id: @list.id) %>
      <%= link_to 'New Bookmark', new_movie_bookmark_path(movie_id: movie.id, list_id: @list.id), class: 'btn btn-primary' %>
      <%= link_to 'Remove', bookmark_path(bookmark), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
    <% end %>
  </div>
  <%= link_to 'Edit', edit_list_path(@list), class: 'btn btn-secondary' %>
  <%= link_to 'Destroy', list_path(@list), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
  <%= link_to 'New Bookmark', new_movie_bookmark_path(movie_id: @list.movies.first.id, list_id: @list.id), class: 'btn btn-primary' %>
</div>

app/views/movies/_form.html.erb
<%= simple_form_for @movie do |f| %>
  <%= f.input :title %>
  <%= f.input :overview %>
  <%= f.input :poster_url %>
  <%= f.input :rating %>
  <%= f.button :submit %>
<% end %>

app/views/movies/_movie.html.erb
<div class="col-md-4">
  <div class="card mb-3">
    <img src="<%= movie.poster_url %>" class="card-img-top" alt="<%= movie.title %>">
    <div class="card-body">
      <h5 class="card-title"><%= movie.title %></h5>
      <p class="card-text"><%= movie.overview %></p>
      <p class="card-text">Rating: <%= movie.rating %></p>
      <%= link_to 'Show', movie_path(movie), class: 'btn btn-secondary' %>
      <%= link_to 'Edit', edit_movie_path(movie), class: 'btn btn-secondary' %>
      <%= link_to 'Destroy', movie_path(movie), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
    </div>
  </div>
</div>

app/views/movies/edit.html.erb
<h1>Edit Movie</h1>

<%= form_with model: @movie do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :overview %>
    <%= f.text_area :overview, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :poster_url %>
    <%= f.text_field :poster_url, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :rating %>
    <%= f.number_field :rating, step: 0.1, min: 0, max: 10, class: "form-control" %>
  </div>
  <%= f.submit "Update Movie", class: "btn btn-primary" %>
<% end %>

<%= link_to "Back", movies_path, class: "btn btn-secondary" %>

app/views/movies/index.html.erb
<h1>Movies</h1>

<div class="container">
  <div class="row">
    <% @movies.each do |movie| %>
      <div class="col-md-4">
        <div class="card mb-4">
          <%= image_tag movie.poster_url, class: "card-img-top" %>
          <div class="card-body">
            <h5 class="card-title"><%= movie.title %></h5>
            <p class="card-text"><%= movie.overview %></p>
            <p class="card-text"><small class="text-muted">Rating: <%= movie.rating %></small></p>
            <%= link_to "Show", movie_path(movie), class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to "Back to Lists", lists_path, class: "btn btn-primary" %>
</div>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= form_with model: @movie do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :overview %>
    <%= f.text_area :overview, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :poster_url %>
    <%= f.text_field :poster_url, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :rating %>
    <%= f.number_field :rating, step: 0.1, min: 0, max: 10, class: "form-control" %>
  </div>
  <%= f.submit "Create Movie", class: "btn btn-primary" %>
<% end %>

<%= link_to "Back", movies_path, class: "btn btn-secondary" %>

app/views/movies/show.html.erb
<div class="container">
  <h1><%= @movie.title %></h1>
  <div class="row">
    <div class="col-md-4">
      <img src="<%= @movie.poster_url %>" class="img-fluid" alt="<%= @movie.title %>">
    </div>
    <div class="col-md-8">
      <p><%= @movie.overview %></p>
      <p>Rating: <%= @movie.rating %></p>
      <p>Lists: <%= @movie.lists.map(&:name).join(", ") %></p>
      <%= link_to 'Go back', lists_path(@list), class: 'btn btn-primary' %>
      <%= link_to 'Edit', edit_movie_path(@movie), class: 'btn btn-secondary' %>
      <%= link_to 'Destroy', movie_path(@movie), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
    </div>
  </div>
</div>